"use client";
import { useState } from "react"; import { useRouter } from "next/navigation"; import { Sparkles, Check } from "lucide-react"; import { useShopStore } from "@/store/useShopStore"; import { coinValue, maxCoinsUsable } from "@/lib/magicCoins";
export default function Checkout(){const router=useRouter(); const {cart,coins,applyCoupon,coupon,placeOrder}=useShopStore(); const subtotal=cart.reduce((a,x)=>a+x.product.price*x.quantity,0); const [used,setUsed]=useState(0); const [code,setCode]=useState(""); const [loading,setLoading]=useState(false); const [step,setStep]=useState(1); const discount=coupon?.discount||0; const total=Math.max(0,subtotal-discount-coinValue(used)); if(!cart.length)return <main className="container py-28 text-center"><h1 className="serif text-4xl">Your cart is empty</h1></main>;
 const submit=()=>{setLoading(true);setTimeout(()=>{const o=placeOrder(used);router.push(`/order-success?id=${o.id}`)},1200)};
 return <main className="container py-12"><h1 className="serif text-5xl">Checkout</h1><div className="flex gap-2 mt-7 mb-10 text-xs">{["Address","Delivery","Rewards","Payment","Review"].map((x,i)=><div key={x} className={`flex-1 border-b-2 pb-3 ${step>i?"border-burgundy text-burgundy":"border-black/10 text-black/40"}`}>{i+1}. {x}</div>)}</div><div className="grid lg:grid-cols-[1fr_360px] gap-10"><div className="bg-white p-6 md:p-8">
 {step===1&&<><h2 className="serif text-3xl">Delivery address</h2><div className="grid md:grid-cols-2 gap-4 mt-6">{["Full name","Phone","Email","Address","City","State","PIN code"].map(x=><input key={x} required placeholder={x} className="border-b p-3 outline-none bg-transparent"/>)}</div><button onClick={()=>setStep(2)} className="bg-plum text-white px-6 py-3 mt-8 text-xs tracking-widest">CONTINUE</button></>}
 {step===2&&<><h2 className="serif text-3xl">Delivery method</h2><label className="block border p-4 mt-6"><input type="radio" defaultChecked name="d"/> Standard delivery · 3–5 days · Free</label><label className="block border p-4 mt-3"><input type="radio" name="d"/> Express delivery · 1–2 days · ₹149</label><button onClick={()=>setStep(3)} className="bg-plum text-white px-6 py-3 mt-8 text-xs tracking-widest">CONTINUE</button></>}
 {step===3&&<><h2 className="serif text-3xl">Magic Coins</h2><p className="mt-3 text-sm text-black/55">Available balance: {coins} ✨</p><div className="mt-6 border p-5"><div className="flex justify-between"><span>Use coins</span><span>{used} coins</span></div><input type="range" min="0" max={maxCoinsUsable(coins,Math.max(0,subtotal-discount))} step="10" value={used} onChange={e=>setUsed(Number(e.target.value))} className="w-full mt-5"/><p className="text-xs text-black/45 mt-2">Discount: ₹{coinValue(used)}</p></div><button onClick={()=>setStep(4)} className="bg-plum text-white px-6 py-3 mt-8 text-xs tracking-widest">CONTINUE</button></>}
 {step===4&&<><h2 className="serif text-3xl">Payment</h2><div className="grid gap-3 mt-6">{["UPI","Credit / Debit Card","Net Banking","Wallet","Cash on Delivery"].map(x=><label key={x} className="border p-4"><input type="radio" name="pay" defaultChecked={x==="UPI"}/> {x}</label>)}</div><p className="text-xs text-burgundy mt-5">Demo payment only — no real money is charged.</p><button onClick={()=>setStep(5)} className="bg-plum text-white px-6 py-3 mt-8 text-xs tracking-widest">REVIEW ORDER</button></>}
 {step===5&&<><h2 className="serif text-3xl">Review & place order</h2><div className="mt-6 text-sm grid gap-3"><p>{cart.length} item(s)</p><p>Standard delivery</p><p>Payment: Demo UPI</p><p>Magic Coins used: {used}</p></div><button disabled={loading} onClick={submit} className="bg-burgundy disabled:opacity-60 text-white w-full py-4 mt-8 text-xs tracking-widest">{loading?"PROCESSING DEMO PAYMENT...":"PLACE ORDER"}</button></>}
 </div><aside className="bg-white p-6 h-fit"><h2 className="serif text-2xl">Summary</h2><div className="flex justify-between mt-5 text-sm"><span>Subtotal</span><span>₹{subtotal.toLocaleString("en-IN")}</span></div><div className="flex gap-2 mt-5"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Coupon code" className="border p-2 flex-1 uppercase"/><button onClick={()=>applyCoupon(code,subtotal)} className="bg-plum text-white px-3 text-xs">APPLY</button></div>{coupon&&<p className="text-xs text-green-700 mt-2">Coupon {coupon.code} applied: ₹{discount} off</p>}<div className="border-t mt-5 pt-5 flex justify-between font-semibold"><span>Total</span><span>₹{total.toLocaleString("en-IN")}</span></div><div className="text-xs text-burgundy mt-3 flex gap-1"><Sparkles size={14}/> Demo rewards are credited after order placement.</div></aside></div></main>}